export const authConstants = {
	LOGIN_REQUEST: 'LOGIN_REQUEST',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAILURE: 'LOGIN_FAILURE',

	FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
	FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
	FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',

	RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
	RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
	RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

	RESET_SERVER_ERROR: 'RESET_SERVER_ERROR',
};
